.PHONY: clean All

All:
	@echo "----------Building project:[ base85_test - Debug ]----------"
	@"$(MAKE)" -f  "base85_test.mk"
clean:
	@echo "----------Cleaning project:[ base85_test - Debug ]----------"
	@"$(MAKE)" -f  "base85_test.mk" clean
